server:
  port: 8081

spring:
  application:
    name: java-ai
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB

file:
  upload:
    dir: D:/tmp


